### ISSUE TITLE
Whatever happend to this project?

### ISSUE THREAD

**Issue by LemmusLemmus** [KeyPuncher/EasyPair#1]
Whatever happend to this project?
As a side question, how did this project differ from the pair function of the dolphin emulator? Would it make sense to use the dolphin emulator for connecting the Wiimotes to the PC and then using the Wiimotes with WiinUPro?

**Comment by KeyPuncher** [comment]
This is the wrong repository.
https://github.com/KeyPuncher/Easy-Pair

This was integrated into WiinUPro and WiinUSoft.
I'm not sure how it differs from dolphin as I've never looked at.
You could certainly use dolphin to connect them first, have you had success with dolphin where there were issues with WiinUPro?

**Comment by LemmusLemmus** [comment]
Oh, sorry. I didn't notice the other one.

For some reason trying to connect using the built in sync feature doesn't work for me anymore (wiinupro doesn't require connecting the device through windows settings prior, right?) I used dolphin to connect the wiimotes before anyhow since it more reliably connects the wiimotes for some reason.

**Comment by LemmusLemmus** [comment]
WiinUPro not detecting my wiimote is probably not the fault of wiinUPro itself, but rather of Windows. Windows wouldn't detect my device either. Despite this dolphin quickly connects to my wiimote, I don't know what's up with that.
